import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { BaseVideoModel } from '../BaseVideoModel.js';
import { runFfmpeg, runFfmpegCommand } from '../../../utils/ffmpeg.js';
import { getStorageProvider } from '../../storage/index.js';
import { Video } from '../../../models/Video.model.js';
import { VIDEO_STATUS } from '../../../constants/enums.js';

const MOCK_LABEL = 'MOCK OUTPUT — NOT REAL AI GENERATION';

/**
 * DevelopmentMockAdapter — proves the entire generation pipeline (queue →
 * worker → "model" → ffmpeg → storage → Video record → job completion)
 * works end to end without any GPU or trained model. It generates a real,
 * short test-pattern video via ffmpeg with the label above burned directly
 * into the frame, so there is no way for this output to be mistaken for
 * real AI-generated content downstream (SRS Phase 10 critical_rule).
 *
 * User prompt text is deliberately NEVER interpolated into the ffmpeg
 * filter graph — only this fixed, hard-coded label is drawn — which sidesteps
 * any need to escape arbitrary user text for drawtext's filter syntax
 * entirely, rather than attempting to sanitize it.
 */
export class DevelopmentMockAdapter extends BaseVideoModel {
  async load() {
    // No model weights to load — intentionally instant.
  }

  async validateInput({ job, model }) {
    if (!model.capabilities.includes(job.type)) {
      throw Object.assign(new Error(`Mock adapter's model does not support "${job.type}"`), {
        code: 'INVALID_INPUT',
      });
    }
    if (job.type !== 'text-to-video' && job.inputFiles.length === 0) {
      throw Object.assign(new Error(`"${job.type}" requires at least one input file`), {
        code: 'INVALID_INPUT',
      });
    }
  }

  async generate({ job, model, onProgress }) {
    await this.validateInput({ job, model });

    const durationSeconds = clamp(job.parameters?.durationSeconds ?? 5, 2, 10);
    const resolution = model.supportedResolutions.includes(job.parameters?.resolution)
      ? job.parameters.resolution
      : model.supportedResolutions[0] || '1280x720';

    const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ai-video-mock-'));
    const videoPath = path.join(workDir, 'output.mp4');
    const thumbnailPath = path.join(workDir, 'thumbnail.jpg');

    try {
      await onProgress?.(10);

      // '-preset veryfast' measured ~2.5x faster encode than the libx264
      // default ('medium') for a 5s 720p clip in this environment, with
      // negligible output size difference — this mock's output is a
      // disposable test-pattern clip, not a quality-sensitive final
      // product, so trading encode speed for compression efficiency is
      // the right tradeoff here specifically (a real model adapter's
      // output would warrant different settings).
      await runFfmpeg([
        '-f', 'lavfi', '-i', `testsrc=size=${resolution}:duration=${durationSeconds}:rate=24`,
        '-f', 'lavfi', '-i', `sine=frequency=440:duration=${durationSeconds}`,
        '-vf',
        `drawtext=text='${MOCK_LABEL}':fontcolor=white:fontsize=28:` +
          `x=(w-text_w)/2:y=(h-text_h)/2:box=1:boxcolor=black@0.6`,
        '-c:v', 'libx264', '-preset', 'veryfast', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest',
        '-y', videoPath,
      ]);

      await onProgress?.(60);

      await runFfmpegCommand('ffmpeg', [
        '-hide_banner', '-loglevel', 'error',
        '-i', videoPath, '-ss', '00:00:01', '-vframes', '1', '-y', thumbnailPath,
      ]);

      await onProgress?.(80);

      const storage = getStorageProvider();
      const keyPrefix = `videos/${job.owner.toString()}/${job._id.toString()}`;
      const [videoAsset, thumbAsset] = await Promise.all([
        storage.saveFile(videoPath, `${keyPrefix}/output.mp4`),
        storage.saveFile(thumbnailPath, `${keyPrefix}/thumbnail.jpg`),
      ]);

      const video = await Video.create({
        owner: job.owner,
        project: job.project,
        generationJob: job._id,
        aiModel: model._id,
        type: job.type,
        title: deriveTitle(job.prompt),
        status: VIDEO_STATUS.READY,
        fileUrl: videoAsset.url,
        fileKey: videoAsset.key,
        thumbnailUrl: thumbAsset.url,
        thumbnailKey: thumbAsset.key,
        durationSeconds,
        resolution,
        fileSizeBytes: videoAsset.sizeBytes,
        format: 'mp4',
        prompt: job.prompt,
        negativePrompt: job.negativePrompt,
        metadata: {
          mock: true,
          label: MOCK_LABEL,
          note: 'Generated by DevelopmentMockAdapter — not a real AI model.',
        },
      });

      await onProgress?.(100);

      return { videoId: video._id, thumbnailUrl: thumbAsset.url };
    } finally {
      await fs.rm(workDir, { recursive: true, force: true });
    }
  }

  async cancel() {
    // The mock's ffmpeg calls run to completion within seconds and aren't
    // tracked per-job for interruption — real cancellation of an in-flight
    // generation is meaningful once a real, long-running adapter exists
    // (Phase 12+). No-op here rather than pretending to interrupt anything.
    return false;
  }

  async cleanup() {
    // Temp files are removed at the end of generate() itself (finally
    // block above) — nothing persists between calls for this adapter.
  }

  getCapabilities() {
    return {
      generationTypes: ['text-to-video', 'image-to-video', 'text-image-to-video'],
      resolutions: ['1280x720', '854x480'],
      durationsSeconds: [2, 3, 5, 8, 10],
    };
  }
}

function clamp(value, min, max) {
  const n = Number(value);
  if (Number.isNaN(n)) return min;
  return Math.min(max, Math.max(min, n));
}

function deriveTitle(prompt) {
  if (!prompt) return 'Untitled generation';
  const trimmed = prompt.trim();
  return trimmed.length > 80 ? `${trimmed.slice(0, 77)}...` : trimmed;
}
